require('plugins.edit.comment')
require('plugins.edit.surround')
require('plugins.edit.switch')
require('plugins.edit.autotag')
require('plugins.edit.avante')
require('plugins.edit.claude')
require('plugins.edit.opencode')
