require('packman').setup({
  { import = 'plugins.theme' },
  { import = 'plugins.lsp' },
  { import = 'plugins.completion' },
  { import = 'plugins.debugging' },
  { import = 'plugins.format' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.edit' },
  { import = 'plugins.ui' },
  { import = 'plugins.layout' },
  { import = 'plugins.navigation' },
  { import = 'plugins.git' },
  { import = 'plugins.workspace' },
  { import = 'plugins.docs' },
  { import = 'plugins.tools' },
})
