require('plugins.theme')
require('plugins.lsp')
require('plugins.completion')
require('plugins.debugging')
require('plugins.format')

require('plugins.treesitter')
require('plugins.edit')
require('plugins.ui')
require('plugins.layout')
require('plugins.navigation')
require('plugins.git')
require('plugins.workspace')
require('plugins.docs')
require('plugins.tools')
